services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    image: 'redis:latest'
#    ports:
#      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  blocks-indexer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: blocks-indexer
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy

  pancake-relay:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: pancake-relay
    env_file:
      - .env
    restart: unless-stopped
    scale: 4
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  swaps-consumer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: swaps-consumer
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  redis-data:
  rabbitmq-data:
